= Installation 

== Requirements

Nextflow can be used on any POSIX compatible system (Linux, OS X, etc).
It requires Bash and
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java
8 (or later)] to be installed.

Optional requirements:

* https://www.docker.com/[Docker] engine 1.10.x (or later) 
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later, optional)
* https://conda.io/[Conda] 4.5 (or later, optional) 
* http://www.graphviz.org/[Graphviz] (optional)
* AWS Batch computing environment properly configured (optional)

== Nextflow Installation

Nextflow is distributed as a self-contained executable package, which
means that it does not require any special installation procedure.

It only needs two easy steps:

1. Download the executable package by using the command shown below. 
It will create the `nextflow` main executable file in the current directory.
+
[source,cmd]
----
curl https://get.nextflow.io | bash
----

2. Finally, move the `nextflow` file to a directory accessible by
your `$PATH` variable (this is only required to avoid remembering and
typing the full path to `nextflow` each time you need to run it).
+
[source,cmd]
----
mv nextflow ~/bin
----

3. Check everything is fine running the command: 
+
[source,cmd]
----
nextflow info
----

[TIP]
====
Alternatively Nextflow can also be installed using Conda package managed 
using the command:
    
[source,cmd]
----
conda install nextflow
----
====
