= Bonus 

== Run a pipeline from a GitHub repository

Nextflow allows the execution of a pipeline project directly from a GitHub repository (or similar services eg. BitBucket and GitLab).

This simplifies the sharing and the deployment of complex projects and tracking changes in a consistent manner.

The following GitHub repository hosts a complete version of the workflow introduced in this tutorial:

https://github.com/nextflow-io/rnaseq-nf

You can run it by specifying the project name as shown below:

[source,cmd]
----
nextflow run nextflow-io/rnaseq-nf -with-docker
----

It automatically downloads it and store in the `$HOME/.nextflow` folder.


Use the command info to show the project information, e.g.:

[source,cmd]
----
nextflow info nextflow-io/rnaseq-nf
----

Nextflow allows the execution of a specific revision of your project by using the `-r` command line option. For Example:

[source,cmd]
----
nextflow run nextflow-io/rnaseq-nf -r dev
----

Revision are defined by using Git tags or branches defined in the project repository.

This allows a precise control of the changes in your project files and dependencies over time.


== Metrics and reports 

Nextflow is able to produce multiple reports and charts providing several runtime metrics 
and execution information. 

Run the https://github.com/nextflow-io/rnaseq-nf[rnaseq-nf] pipeline
previously introduced as shown below: 

[source,cmd]
----
nextflow run rnaseq-nf -with-docker -with-report -with-trace -with-timeline -with-dag dag.png
----

The `-with-report` option enables the creation of the workflow execution report. Open 
the file `report.html` with a browser to see the report created with the above command. 

The `-with-trace` option enables the create of a tab separated file containing runtime 
information for each executed task. Check the content of the file `trace.txt` for an example.

The `-with-timeline` option enables the creation of the workflow timeline report showing 
how processes where executed along time. This may be useful to identify most time consuming 
tasks and bottlenecks. See an example at https://www.nextflow.io/docs/latest/tracing.html#timeline-report[this link]. 

Finally the `-with-dag` option enables to rendering of the workflow execution direct acyclic graph 
representation. Note: this feature requires the installation of http://www.graphviz.org/[Graphviz] in your computer. 
See https://www.nextflow.io/docs/latest/tracing.html#dag-visualisation[here] for details.

TIP: The public IP address of your computer can be obtained with the command `myip`. 

Note: runtime metrics may be incomplete for run short running tasks as in the case of this tutorial.

